apiVersion: v1
kind: Secret
metadata:
  name: expense-secrets
  namespace: expense-tracker
type: Opaque
stringData:
  # Using stringData so you don't need to manually base64 encode
  MONGO_URI: mongodb://mongo-service:27017/expensetracker
